### ISSUE TITLE
GetPlayerWeapon and related

### ISSUE THREAD

**Issue by AliLogic** [openmultiplayer/samp-bugs#17]
Weapon related natives don't work or send updates when a player is in a vehicle - this includes GetPlayerWeapon, GetPlayerWeaponData (which also sends weapons with empty ammo in the data) and more.

**Comment by Alasnkz** [comment]
`GetPlayerWeaponData (which also sends weapons with empty ammo in the data) `
We've fixed that, we ignore (or remove) weapons that have no ammo on the server.

**Comment by NexiusTailer** [comment]
> this includes GetPlayerWeapon, GetPlayerWeaponData (which also sends weapons with empty ammo in the data) `and more`.

I think it's important to know which exactly functions also works incorrectly besides already listed

**Comment by AliLogic** [comment]
Glad.
