### ISSUE TITLE
OnVehicleSpawn

### ISSUE THREAD

**Issue by AliLogic** [openmultiplayer/samp-bugs#18]
This callback, by name means when a vehicle spawns, but instead is only called when a vehicle is re-spawned, I believe it should also be called when a vehicle is spawned for the first time or make the callback be called "OnVehicleRespawn".

**Comment by Alasnkz** [comment]
Is there any purpose for it to be called for a new vehicle? After all, you are creating the vehicle so you would know when its spawned?

**Comment by AliLogic** [comment]
Then just rename it?

**Comment by Y-Less** [comment]
There are good reasons to call it after both - saves duplicating code needed to set up certain parameters for a vehicle just spawned.

**Comment by AliLogic** [comment]
Yeah.
