### ISSUE TITLE
[Server] GMX Command

### ISSUE THREAD

**Issue by Zorono** [openmultiplayer/samp-bugs#27]
`OnPlayerDisconnect` isn't being called when `gmx` command is running and all the filterscripts stop working untill `reloadfs {FILTERSCRIPT_NAME}` command get called...

**Comment by NexiusTailer** [comment]
Player are actually not leave the samp-server while gamemodes change (gmx). So it's probably a bug in your filterscripts which don't consider OnGameModeInit & OnGameModeExit callbacks.
