### ISSUE TITLE
OnPlayerExitVehicle

### ISSUE THREAD

**Issue by polygxn** [openmultiplayer/samp-bugs#3]
OnPlayerExitVehicle is not called when a player gets killed inside a vehicle.

Also, these: http://prntscr.com/nerbgu

**Comment by NexiusTailer** [comment]
This is not a bug, because this callback is called only when a player presses the enter button just to **try** to exit the current vehicle by himself, it is not detecting the actual exit from the car.

**Comment by AGraber** [comment]
Yes, this and OnPlayerEnterVehicle only get triggered when the player gracefully starts to do one of both, which is intended behaviour.

**Comment by ghost** [comment]
Makes sense, my bad. I just realized there is OnPlayerStateChange for this.
