### ISSUE TITLE
[Server] SetSpawnInfo doesn't set player's team

### ISSUE THREAD

**Issue by sklawik** [openmultiplayer/samp-bugs#32]
We have SetSpawnInfo function which has argument: Team.
If we have both players with same team, player 1 in team 0 and player 2 in team 0 they can't damage themselves.
If we set it only by SetSpawnInfo, player in "same team" can damage themselves, but if we use SetPlayerTeam instead we will fix that.
So the fix is to use:
SetSpawnInfo..
// and below
SetPlayerTeam

**Comment by Y-Less** [comment]
Well that's not quite the solution - the `SetPlayerTeam` would have to go in `OnPlayerSpawn` instead.  But otherwise yes, thanks.
