### ISSUE TITLE
"Unacceptable Nickname" on Ubuntu server 16 or newer

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/samp-bugs#40]
Original thread: 
https://forum.sa-mp.com/showthread.php?t=669343
https://burgershot.gg/showthread.php?tid=1164&pid=7832#pid7832

Don't know if this true, i might have to test it myself since i'm using Ubuntu 20.04
And maybe it occurs on newest linux kernel, but i'm not sure about that.

**Comment by Alasnkz** [comment]
`with ubuntu 18 operating system, after 2 min kick all players with the following error`
Seems to be the known 4.9-.19 bug with UDP.
