### ISSUE TITLE
[NO LABEL] Splat Bug

### ISSUE THREAD

**Issue by ichiwi** [openmultiplayer/samp-bugs#43]
There was a common bug within vehicles sync where a player stands on the car and while the car's speeding and takes a turn, you'll be pushed to the door and splat over the vehicle then die immediately.

**Comment by Y-Less** [comment]
That doesn't sound like a bug to me, that sounds like exactly what should happen when you try standing on a speeding car and it takes a sudden turn.  I've never tested it IRL, but maybe you could film a video showing otherwise?

**Comment by ichiwi** [comment]
Unfortunately, you'll fall immediately - causing serious injury, however, the game physics in singleplayer allows you to stand on a moving vehicle that an NPC is driving, but there is a possibility that you fall off if he takes an immediate turn quickly, but without dying just falling off the car. I've tried it with a guy with almost my ping and packetloss, we didn't experience the splat bug (I fell sometimes off the car but didn't die), sounds like a synchronization bug to me. But if a guy has a poor connection, most likely you will experience the bug.

The main idea of this, maybe vehicle sync can be better in open.mp. If it's not possible, then it's okay. Not quite of a big deal.
